### ISSUE TITLE
MimeType.byFileName raises an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by x7airworker** [JavaWebStack/http-server#21]
```
java.lang.ArrayIndexOutOfBoundsException: -1
    at org.javawebstack.httpserver.util.MimeType.byFileName(MimeType.java:71)
    at org.javawebstack.httpserver.handler.StaticFileHandler.handle(StaticFileHandler.java:31)
    at org.javawebstack.httpserver.HTTPServer.execute(HTTPServer.java:342)
    at org.javawebstack.httpserver.HTTPServer.lambda$start$1(HTTPServer.java:283)
    at org.javawebstack.httpserver.adapter.undertow.UndertowHTTPSocketServer.lambda$start$1(UndertowHTTPSocketServer.java:50)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
    at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by JanHolger** [comment]
Fixed by #23
